version: '3'
services:
  mysqlmaster:
    image: mysql:5.7.25
    container_name: mysql-master
    restart: always
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - net-v1
    volumes:
      - ./data/mysql-master:/var/lib/mysql/
      - ./config/mysql-master:/etc/mysql/conf.d/

 mysqlslave:
   image: mysql:5.7.25
   container_name: mysql-slave
   restart: always
   ports:
     - 3307:3306
   environment:
     - "MYSQL_ROOT_PASSWORD=root"
   networks:
     - net-v1
   depends_on:
     - mysqlmaster
   volumes:
     - ./data/mysql-slave:/var/lib/mysql/
     - ./config/mysql-slave:/etc/mysql/conf.d/

 mysqlconfig:
   image: mysql:5.7.25
   container_name: mysql-config
   environment:
     - "MYSQL_SLAVE_PASSWORD=root"
     - "MYSQL_MASTER_PASSWORD=root"
     - "MYSQL_ROOT_PASSWORD=root"
     - "MYSQL_REPLICATION_USER=repl"
     - "MYSQL_REPLICATION_PASSWORD=root"
     - "MYSQL_MASTER_IP=mysqlmaster"
     - "MYSQL_SLAVE_IP=mysqlslave"
   networks:
     - net-v1
   depends_on:
     - mysqlmaster
     - mysqlslave
   volumes:
     - ./mysql_connector.sh:/tmp/mysql_connector.sh
   command: /bin/bash -x /tmp/mysql_connector.sh

networks:
  net-v1:
    external:
      name: mynetwork
volumes:
  esdata6:
